README.md
=> Removing extraneous text in readme

src/common/_locales/de/strings.json, src/common/_locales/es/strings.json, src/common/_locales/es_419/strings.json, src/common/_locales/fr/strings.json, src/common/_locales/it/strings.json, src/common/_locales/ja/strings.json, src/common/_locales/ko/strings.json, src/common/_locales/nl/strings.json, src/common/_locales/pl/strings.json, src/common/_locales/pt_BR/strings.json, src/common/_locales/pt_PT/strings.json, src/common/_locales/ru/strings.json, src/common/_locales/zh_CN/strings.json, src/common/_locales/zh_TW/strings.json
=> Updating translations for various languages

src/manifest.yml
Noticed the manifest version was not in sync with the release.
=> Fix Manifest version to properly reflect release

src/manifest.yml
Release 3.0.1.0 - Asimov - Foundation
- Add check for system pages (chrome://extension) and avoid attempting to save them
- Add Swap tabs functionality to avoid zombie tab references
- Changed tab status caching so everything is keyed on the tab as opposed to the save hash.  This keeps the state cleaner.
- Fixed Zombie Tags on subsequent page saves
- Fixed Zombie Recs on subsequent page saves
- Fixed Tab messaging so frame updates are sent to active tab as opposed to all tabs (which was creating the slowdown with high volume tabs)
- Removed Save Hashing since we are not persisting saves
=> Update Manifest to 3.0.1.0

src/containers/save/_save.js, src/containers/save/save.app.js
Fix Recs showing up on browsers set to non-english (we only support English language recs at the moment)
Fast fix before we make a larger release
=> Fix on save recs showing on non english language 

src/manifest.yml
Release 3.0.2.0 - Asimov - Forward The Foundation
- Added sponsored content header for more clarity
- Added sponsored content actions (click, hide, about, hide all)
- Updated recommendations header to avoid misconstruing endorsement
- Updated Analytics for recommendation clicks
=> Updating Manifest for release

src/containers/save/_save.js, src/manifest.yml
Release 3.0.1.0 - Asimov - Forward the Foundation
- Fixed close panel not firing due to comment oversight
=> Release/3.0.2.1 Asimov - Forward the Foundation

src/common/interface.js, src/containers/auth/login.js, src/containers/auth/logout.js, src/containers/background/_setup.js, src/containers/background/background.js, src/containers/options/options.js, src/containers/save/recommendations/_recommendations.js, src/containers/save/recommendations/list/item.js, src/containers/save/save.js, src/manifest.yml
=> 3.0.3.0 - Asimov - Foundation and Empire

public/index.html
=> Fix typo in index.html

Safari/Save to Pocket/Save to Pocket Extension/Info.plist
Add necessary API to bridge Swift/JS communication. 
Instructions for how to register for the event from Javascript are provided [here](https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_info_property_list_keys/adjusting_settings_for_contextual_menu_items):
```
document.addEventListener("saveToPocket", handleContextMenu, false);
function handleContextMenu(event) {
... etc ...
}
```
=> [P19-1160] Add Swift Bridge

_safari/Save to Pocket Extension/Common/API.swift, _safari/Save to Pocket Extension/Common/Actions.swift, _safari/Save to Pocket Extension/Common/Structures.swift, _safari/Save to Pocket Extension/Info.plist, _safari/Save to Pocket Extension/SafariExtensionHandler.swift, _safari/Save to Pocket Extension/script.js
Want to have a skeleton of actions so individual contributors can work within a common expectation.
#101 
This is PR is reliant on #106 in terms of setting up proper structure conventions and should be reviewed prior to reviewing this one.
=> project(safari): structure message dispatch

.storybook/addons.js, .storybook/config.js, README.md, package.json, yarn.lock
Add storybooks for react
Using the manual setup outlined https://storybook.js.org/docs/guides/guide-react/ with a few options to locate config in a config directory
=> build(local): add storybook for react

_safari/Save to Pocket/Base.lproj/Main.storyboard, _safari/Save to Pocket/Info.plist, _safari/Save to Pocket/ViewController.swift
Add a hover state for the launcher button
=> refactor(safari): updating launcher button to have hover state

src/common/api/saving/archive.js, src/common/api/saving/remove.js, src/common/api/saving/save.js, src/containers/save/_save.js
Reverts Pocket/extension-save-to-pocket#140
=> Revert "update(save): add js action info context parameters to api call"

src/components/modules/autohide/autohide.hoc.js, src/containers/safari/app.container.js, src/containers/safari/app.state.js, src/containers/safari/save.state.js
Fix discrepancies with the pop-up display
=> fix(popup): fix popup behavior on user actions

src/containers/safari/app.container.js
Close the door-hanger when the users presses enter without an active tag.
=> feat(safari): add close panel action to doorhanger

_safari/Save to Pocket/Base.lproj/Main.storyboard
Change horizontal alignment of `Need Help?` to 222pt off of leading container.
Closes #178
=> fix(safari): Needs Help button is 222 pt from leading edge

_safari/Save to Pocket Extension/Info.plist, _safari/Save to Pocket.xcodeproj/project.pbxproj, _safari/Save to Pocket/Info.plist
Resolves validation errors in app submission.
=> feat(safari): ASC Validation

_safari/Save to Pocket Extension/de.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/es-419.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/es.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/fr-CA.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/fr.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/it.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/ja.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/ko.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/nl-NL.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/pl.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/pt-BR.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/pt-PT.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/ru.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/zh-Hans.lproj/InfoPlist.strings, _safari/Save to Pocket Extension/zh-Hant.lproj/InfoPlist.strings, _safari/Save to Pocket/de.lproj/Main.strings, _safari/Save to Pocket/es-419.lproj/Main.strings, _safari/Save to Pocket/es.lproj/Main.strings, _safari/Save to Pocket/fr-CA.lproj/Main.strings, _safari/Save to Pocket/fr.lproj/Main.strings, _safari/Save to Pocket/it.lproj/Main.strings, _safari/Save to Pocket/ja.lproj/Main.strings, _safari/Save to Pocket/ko.lproj/Main.strings, _safari/Save to Pocket/nl-NL.lproj/Main.strings, _safari/Save to Pocket/pl.lproj/Main.strings, _safari/Save to Pocket/pt-BR.lproj/Main.strings, _safari/Save to Pocket/pt-PT.lproj/Main.strings, _safari/Save to Pocket/ru.lproj/Main.strings, _safari/Save to Pocket/zh-Hans.lproj/Main.strings, _safari/Save to Pocket/zh-Hant.lproj/Main.strings
Add localized copy.
Closes #129
=> feat(safari): launcher localization

_safari/Save to Pocket Extension/Save to Pocket Extension.entitlements, _safari/Save to Pocket Extension/Save_to_Pocket_Extension.entitlements, _safari/Save to Pocket.xcodeproj/project.pbxproj, _safari/Save to Pocket/Save to Pocket.entitlements, _safari/Save to Pocket/Save_to_Pocket.entitlements
Insert purpose of pull request
=> feat(safari): update code signing identity and entitlements

_safari/Save to Pocket/de.lproj/Main.strings, _safari/Save to Pocket/es-419.lproj/Main.strings, _safari/Save to Pocket/es.lproj/Main.strings, _safari/Save to Pocket/fr-CA.lproj/Main.strings, _safari/Save to Pocket/fr.lproj/Main.strings, _safari/Save to Pocket/it.lproj/Main.strings, _safari/Save to Pocket/ja.lproj/Main.strings, _safari/Save to Pocket/ko.lproj/Main.strings, _safari/Save to Pocket/nl-NL.lproj/Main.strings, _safari/Save to Pocket/pl.lproj/Main.strings, _safari/Save to Pocket/pt-BR.lproj/Main.strings, _safari/Save to Pocket/pt-PT.lproj/Main.strings, _safari/Save to Pocket/ru.lproj/Main.strings, _safari/Save to Pocket/zh-Hans.lproj/Main.strings, _safari/Save to Pocket/zh-Hant.lproj/Main.strings
Update localized strings
Closes #181
=> feat(safari): update localized strings

src/common/helpers.js
Top image should take precedence over image array when choosing a thumbnail to accompany the article
=> fix(recommendations): image precedence

_chromium/manifest.yml
We are not using the notifications api, let's remove this permissions request.
This truly wasn't necessary.
=> fix(permissions): remove notifications permissions value

src/common/_locales/de/strings.json, src/common/_locales/en/strings.json, src/common/_locales/es/strings.json, src/common/_locales/es_419/strings.json, src/common/_locales/fr/strings.json, src/common/_locales/it/strings.json, src/common/_locales/ja/strings.json, src/common/_locales/ko/strings.json, src/common/_locales/nl/strings.json, src/common/_locales/pl/strings.json, src/common/_locales/pt_BR/strings.json, src/common/_locales/pt_PT/strings.json, src/common/_locales/ru/strings.json, src/common/_locales/zh_CN/strings.json, src/common/_locales/zh_TW/strings.json
=> fix(localization): adding updated localized strings

package.json, src/pages/options/options.js
=> fix(package): bump package version to official release

package.json, src/common/api/_request/request.js, src/common/api/auth/authorize.js, src/common/api/auth/guid.js, src/manifest.json, src/pages/background/index.js, src/pages/background/postSave.js, src/pages/background/userActions.js
Adding Sentry error reporting to determine what would be causing auth issues.
Most of this was completed by Joel, taken over the finish line by me.
=> fix(auth): add sentry error reporting to auth
