yarn.lock
The lock file was referencing and old version of the build tools and would throw an error.
=> Updating lock file to use new build tools

src/containers/save/_save.js
ItemID was not getting passed through properly for archive and remove.
=> Fixing archive/remove so the item_id gets passed

src/manifest.yml
Fix collisions that occur with a pre-loaded iframe
The way we traditionally injected content scripts into all sites caused some issue that were easily resolved my moving to an on-demand model.  Since we already had on-demand functionality in place to handle pages that existed prior to extension install, simply removing that script from the content_scripts in the manifest moves us to fully on-demand for all sites.
=> Removing js injection on all sites

src/containers/background/_tabs.js, src/containers/background/background.js
Tabs would be marked as `ready` after being loaded.  This had the potential to cause high memory consumption on a user with a great many tabs open.  This is being switched to a less aggressive version where we only text readiness on a save request.  We drop tabs when they are closed.
The initial idea was operating under the assumption of a certain number of tabs.  This eliminates that assumption and take into account users with high volume of tabs.
=> Update/Eliminate pre-emptive tab storage

src/manifest.yml
Release 3.0.0.11
-  Eliminate pre-emptive tab storage (#30)
*  Tabs would be marked as `ready` after being loaded.  This had the potential to cause high memory consumption on a user with a great many tabs open.  This is being switched to a less aggressive version where we only test readiness on a save request. 
- Fix/autocomplete trigger (#29)
* Updating `Enter` check for highlightedIndex
* Fix autocomplete now shows on first letter input
* Updating tag storage to utilize existing tags
- This add the existing `tags` to the `stored_tags` and removes the `tags` from the local storage.  Basically just changing the key for stored tags.
* Fixing close panel on double enter - Removed the delay in close on double enter.
* Updating typeahead open trigger to include result check
-  Fix/item tag …
=> Release 3.0.0.11

src/common/api/index.js, src/common/api/saving/tags.js, src/containers/background/_setup.js, src/store/combineSagas.js
When a user logs in the extension fetches previously used tags from the server to hydrate autocomplete tagging list.
=> Adding tag fetch from server when user logs in

src/manifest.yml
Release 3.0.0.12
-  Adding tag fetch from server when user logs in (#35)
*  When a user logs in, the extension fetches previously used tags from the server to hydrate autocomplete tagging list.  This should not affect pre-existing users as we also store these tags locally.  For fresh installs, users will not have their previous tags available to them immediately.  This fixes a regression introduced in 3.0.0.x
=> Updating Manifest to 3.0.0.12

src/containers/save/_save.js
Hot Fix to rectify come commented out code getting pushed live.  The close panel was not accessible. 
This was commented out in order to better test some UI changes and it got left in accidentally.
=> Fixing commented out panel closing

src/containers/save/recommendations/_recommendations.js, src/containers/save/recommendations/list/item.js
This keeps falling out with combined merges... so this is a dedicated PR just for this specific fix.
For the record: We favor `given_url` and are falling back to `resolved_url` when building the feed.
=> Fix Fallback Reccomendation URL

src/Containers/Save/save.state.js
The goal is to improve UX by matching the same timeout as the v3.0.5.
Fix https://getpocket.atlassian.net/browse/P19-511
=> increase timer modal to match current version

_safari/Save to Pocket Extension/Common/API.swift, _safari/Save to Pocket Extension/Common/Utilities.swift, _safari/Save to Pocket Extension/SafariExtensionHandler.swift
Use idiomatic asynchronous dispatch to avoid blocking the main CPU thread
The refactor of `API.request` makes it consistent with idiomatic Swift (insomuch as I know anything about Swift). In the `API.validateAuthCode` function, I created an example of how one can use a dedicated dispatch queue to use dispatch semaphores without blocking the main queue.
=> refactor(auth): idiomatic asynchronous dispatch

_safari/Save to Pocket Extension/Common/API.swift, _safari/Save to Pocket Extension/Common/Structures.swift, _safari/Save to Pocket Extension/Common/Utilities.swift, _safari/Save to Pocket Extension/Info.plist, _safari/Save to Pocket Extension/SafariExtensionHandler.swift, _safari/Save to Pocket Extension/login.js
Add authentication of the Safari App Extension
I have broken out the files into API, Utilities, Structure to keep the logic separate from the dispatcher.  This should allow people less familiar with Swift to interface with the extension handler without getting bogged down.
This branch will be rebased once the PR #104 is completed, so that should be reviewed first.
=> feat(safari): add authenticate user

_safari/Save to Pocket Extension/Common/API.swift, _safari/Save to Pocket Extension/Common/Actions.swift, _safari/Save to Pocket Extension/Common/Structures.swift, _safari/Save to Pocket Extension/Common/Utilities.swift, _safari/Save to Pocket Extension/SafariExtensionHandler.swift, _safari/Save to Pocket.xcodeproj/project.pbxproj
Add Save to Pocket call to the Safari App Extension
This branch will be rebased once the PR #104 is completed, so that should be reviewed first.
=> feat(safari): add save to pocket

src/common/api/saving/archive.js, src/common/api/saving/remove.js, src/common/api/saving/save.js, src/containers/save/_save.js
Fix #139 
The purpose of this PR is to make sure that the analytics context data in the spec https://docs.google.com/spreadsheets/d/15YIc9n0eqOA9soD_NleEqED49Tqy5p4S9a5IHDN8BeI/edit#gid=0 is being passed along in the js api calls.
Update api action handlers to accept the context parameters and add them in the api call.
=> update(save): add js action info context parameters to api call

_safari/Save to Pocket Extension/Common/Actions.swift, _safari/Save to Pocket Extension/SafariExtensionHandler.swift, src/containers/safari/dispatch.js
When a user right clicks on a link and selects `save to pocket`, the app should save that link.  If they click on a part of the page without a link, we should save the page they are clicking on.
=> feat(safari): adding a save via context menu

_safari/Save to Pocket Extension/Common/API.swift
Remove item was passing the wrong action type to the send api.  This fixes that.
=> fix(safari): remove item action

_safari/Save to Pocket Extension/Common/Actions.swift
If the user selects the pocket toolbar on an invalid url we should open their list
=> feat(safari): open 'My List' on invalid url (new tab)

_safari/Save to Pocket Extension/Common/Actions.swift, _safari/Save to Pocket Extension/Common/Structures.swift, _safari/Save to Pocket Extension/Info.plist, _safari/Save to Pocket Extension/SafariExtensionHandler.swift, _safari/Save to Pocket Extension/logout.js, _safari/Save to Pocket.xcodeproj/project.pbxproj
When user logs out of the web app, we should also log them out of the extension.
We are simply injecting a script into the specific url `https://getpocket.com/login`.  This is similar to how we do it on chrome with the exception of the query params `?e=4` This is because the Allowed URL Patterns do not support query parameters.
=> feat(safari): log out of extension when logging out of web app

_safari/Save to Pocket/AppDelegate.swift, _safari/Save to Pocket/Base.lproj/Main.storyboard
Insert purpose of pull request
The "fuzzy" text of the `Finish Setup` button is a byproduct of subpixel alignment. There's not a lot we can do here without blitzing the text directly, which is a bit of hackery I'd prefer to avoid at the last moment before submission.
=> feat(safari): launcher refinements

src/containers/safari/dispatch.js, src/containers/safari/inject.js
On single page apps, the DOM injection has the potential of getting wiped out.  This makes a check that we have the injected DOM elements on every save request.  If we have them, we do nothing, if they are absent we inject them.
=> fix(safari): check dom on save request

_safari/Save to Pocket Extension/Common/API.swift, _safari/Save to Pocket Extension/Common/Actions.swift, _safari/Save to Pocket Extension/SafariExtensionHandler.swift, src/containers/save/_save.js
Fix analytics not passing all context cxt_ui parameters when saving from right click context menu.
The save from right clicking a page needs to pass
```"cxt_ui": "right_click_page"```
The save from right clicking a link needs to pass
```"cxt_ui": "right_click_link"```
The save from clicking the toolbar icon needs to pass
```"cxt_ui": "toolbar"```
```
{
"access_token": "61994fee-72de-6d59-3dd1-2d91cd",
"actions": [{
"url": "https:\/\/www.cnn.com\/us\/live-news\/texas-flooding-september-2019\/index.html",
"action": "add",
"cxt_ui": "right_click_page",
"cxt_premium_status": "1"
}],
"consumer_key": "9346-1e342af73fe11d5174042e9d"
}
```
Add new parameter for ui context to pass to save pocket function as well as pass boolean `is_menu` so that we can differentiate between right click page and …
=> Fix/analytics context on save for cxt_ui param

src/containers/safari/tags.state.js
If a user saves multiple articles on the same page (via context), we should make sure no relic tag suggestions are shown
=> fix(safari): reset tag state on save request

src/containers/safari/dispatch.js
Handle clicks on nested elements in an anchor properly.
Using closest() since it is supported in Safari version we are targeting and several versions back.
=> fix(safari): pass link on contained element click

_safari/Save to Pocket Extension/Info.plist, _safari/Save to Pocket.xcodeproj/project.pbxproj, _safari/Save to Pocket/Base.lproj/Main.storyboard, _safari/Save to Pocket/Info.plist
Make this work. 
Before you do anything, let's validate that you can reproduce the problem. (Note: since I've fixed the signing identities on the server, it's possible that we won't be able to reproduce this problem anymore). 
Under `Window` ... `Organizer`, locate the version of the app that you submitted.
Select `Distribute App`
Select `Copy` ... save to desktop.
Try using the extension. For me, before generating a new signing identity, the launcher would work, but the extension button would not. 
Next, go to Xcode preferences ... `Accounts`
Select `Download Manual Profiles`
Archive the app.
Assuming your previous `Export` failed, verify that this one doesn't. 
Assuming everything works as expected, `Distribute` the app as before.
=> feat(safari): adjust signing identity 

.github/prlint.json
Adding basic lint for branches/pr titles
This will help keep consistency throughout the repo.  These will match commit linting to be added in the future.
=> build(linting): adding pr title lint parameters

_chromium/manifest.yml, src/common/api/saving/recommendations.js, src/components/views/doorhanger/recommendations/list/item.js, src/containers/recs.state.js
Get recommendations from RecIt. Recommendations should be better, and it would allow us to remove the fragile /recs endpoint from feed-machine that is currently serving recommendations to Chrome.
=> feat(recs): update recommendations endpoint to use recit

_chromium/handlersPostSave.js, _chromium/manifest.yml, src/common/api/saving/recommendations.js
Could we swap this to use its own endpoint so it doesn't accidentally get impacted by changes to other endpoint? There isn't a `web_after_article` module right now, so this isn't a huge deal, but better if we can get it right now.
@mmiermans can you confirm the backend is fine with passing arbitrary modules to RecIt?
=> fix(recs): update recs request with correct module and only fetch when resolved id exists

_chromium/manifest.yml, src/containers/inject.js
We received user reports that the HTML elements for the pocket dropdown were being included on every page before a user had saved the page. This was adding unnecessary clutter to the dom. 
We were attempting to inject the elements into the dom twice; once on page load, and once when a user saved the page. I removed the call to the inject script from page load.
The call on page save is here:
https://github.com/Pocket/extension-save-to-pocket/blob/master/src/containers/dispatch.js#L70
=> fix(inject): do not inject html elements until user saves page [FRONT-762]

_chromium/manifest.yml, src/components/views/doorhanger/recommendations/list/item.js
Add UTM tracking to the recs we serve in the Chrome Extension. This would help us see how much traffic those recs are driving to syndicated content, and also allow our publisher partners to more holistically see how much traffic Pocket drives to their sites.
I was not able to confirm whether recommendations are passed to the extension with any existing query params in place, so this solution handles both instances of urls with and without.
=> fix(recommendations): add utm_source query param

src/components/chips/chips.js, src/components/toggle/toggle.js, src/pages/options/options.html, src/pages/options/options.js
Convert emotion to linaria
Note: there are still a few instances of `emotion` and a few things that need to be figured out (see comments below) but I wanted to get this one up before the end of my day and I think everything can be addressed in future PRs. Baby steps.
=> fix(packages): convert emotion to linaria

src/pages/options/options.js
Fix login/logout section not rendering in options page due to async `getSettings` calls
Remove double quotes
=> fix(options): await getSetting calls as they are async

src/components/button/extensions-button.js, src/components/item-preview/item-preview.js, src/pages/injector/app.js, src/pages/injector/globalStyles.js
=> fix(styling): style overrides and specificity

package.json, src/components/button/extensions-button.js, src/components/doorhanger/doorhanger.js, src/components/footer/footer.js, src/components/heading/heading.js, src/components/tagging/tagging.js, src/components/tagging/taginput/taginput.js, src/pages/injector/globalStyles.js, src/pages/options/options.js
Fixes issue https://github.com/Pocket/extension-save-to-pocket/issues/270
Colors are still included on `global`, but scoped specifically to class names so there wouldn't be any style-bleed. 
Removed the `globalVariables` and the `globalReset` variables from `options.js` because they are automatically included in `options.html` with the build css file: `/assets/pocket-save-extension.css`
=> fix(css): scope css color variables to pocket extension class name

src/common/api/_request/request.js, src/pages/background/index.js, src/pages/background/userActions.js, src/pages/login.js
Adding logging to help the Support team troubleshoot auth issues our users are having.
It's difficult to reproduce the auth issues our users are running into, so I've added logging that our Support team can ask for. 
The first bit of logging is for the `getpocket.com/extension_login_success` page. If this page hangs, you can open the console and verify whether there is a stored cookie for `token` or `userId`. These cookies should be created on the previous page.
The second bit of logging is displays the `userId`, `token`, `guid` and where the `guid` originates. The `guid` can originate from `extension` (stored in `chrome.storage`), `site` (stored in a cookie as `sess_guid`), or `server` (fetched from `v3/guid`). There should be 4 values in this object.
The last bit is adding the …
=> fix(auth): adding logging to the auth process for support team [FRONT-1488]

package.json, src/common/api/_request/request.js, src/pages/background/index.js, src/pages/background/userActions.js, src/pages/injector/app.js, src/pages/login.js
We've heard from users that removing the timed dismissal of the Save popover caused problems in their workflow, so I've added the ability to dismiss the popover using the ESCAPE key
I added this at the top `app` level as that's where the open/close state of the popover is stored.
=> fix(app): add ability to dismiss popover with keyboard [FRONT-1506]

src/components/button/extensions-button.js, src/components/footer/footer.js, src/components/heading/heading.js
During the QA process it was discovered that the Header, Footer, and Button icon styles could use some tweaks to prevent style bleed
The sites causing trouble were How-To Geek, and Fox Business Network
=> fix(icon): update the pocket icon to use brand color

package.json, src/_locales/de/messages.json, src/_locales/en/messages.json, src/_locales/es/messages.json, src/_locales/es_419/messages.json, src/_locales/fr/messages.json, src/_locales/it/messages.json, src/_locales/ja/messages.json, src/_locales/ko/messages.json, src/_locales/nl/messages.json, src/_locales/pl/messages.json, src/_locales/pt_BR/messages.json, src/_locales/pt_PT/messages.json, src/_locales/ru/messages.json, src/_locales/zh_CN/messages.json, src/_locales/zh_TW/messages.json, src/common/api/_request/request.js, src/common/api/auth/guid.js, src/common/interface.js, src/components/button/extensions-button.js, src/components/error-message/error-message.js, src/components/footer/footer.js, src/components/heading/heading.js, src/pages/background/index.js, src/pages/background/userActions.js, src/pages/injector/app.js, src/pages/injector/content.js
Addressing errors captured by Sentry.
The storage errors seem to be the biggest culprit with the authentication issues experienced by some users. If Chrome can't `get` or `set` items to the local storage, there is no way to save a user's auth status. 
to be merged into https://github.com/Pocket/extension-save-to-pocket/pull/276
This is a Chrome level error and is related to a user's available disc space when trying to write to `chrome.storage`. There isn't any _real_ documentation on this error provided by Google. In my research I came across another open-source extension where users experienced this issue and it was solved by clearing hard-drive space and rebooting the browser. Not ideal. I've added error handling to our helper function that sets the storage, as well as error logging …
=> fix(storage): add error handling to setting or getting storage
